parameters:
#    freedom_objective.example.class: Freedom\ObjectiveBundle\Example
    # freedom_objective_objective.class: Freedom\ObjectiveBundle\Entity\ObjectiveManager

services:
#    freedom_objective.example:
#        class: %freedom_objective.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    # freedom_objective_objective:
    #     class: "%freedom_objective_objective.class%"
    #     arguments:    ["@security.context", 3]
