objective : 
    type: rest
    resource:     "FreedomApiBundle:Objective"
    name_prefix:  api_objective

step : 
    type: rest
    parent:   objective
    resource:     "FreedomApiBundle:Stepobjective"
    name_prefix:  api_step

advice : 
    type: rest
    parent:   objective
    resource:     "FreedomApiBundle:Advice"
    name_prefix:  api_advice

user : 
    type: rest
    resource:     "FreedomApiBundle:User"
    name_prefix:  api_user

userfollowobjective : 
    type: rest
    resource:     "FreedomApiBundle:Userfollowobjective"
    name_prefix:  api_userfollowobjective

group : 
    type: rest
    resource:     "FreedomApiBundle:Group"
    name_prefix:  api_group