<?php

namespace Freedom\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserfollowobjectiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserfollowobjectiveRepository extends EntityRepository
{
}
