<?php

namespace Freedom\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserlikeobjectiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserlikeobjectiveRepository extends EntityRepository
{
}
