<?php

namespace Freedom\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserlikestepobjectiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserlikestepobjectiveRepository extends EntityRepository
{
}
