<?php

namespace Freedom\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

	//Init filters
	public function addFilters(QueryBuilder $qb, $filters)
	{
		foreach ($filters as $key => $value) {
			$qb->andWhere('u.'.$key.' = :'.$key)->setParameter($key, $value);
		}
		
	}

	public function apiSearch($name, $filters, $offset, $limit, $order_by)
	{

		//Get the order_by's key
		$keys = array_keys($order_by);

	  	$qb = $this->_em->createQueryBuilder();
	  	$qb->select('u')
	    ->from('FreedomUserBundle:User', 'u')
	 	->where('u.username LIKE :name')            
        ->setParameter('name', '%'.$name.'%')
        ->orderBy('u.'.$keys[0], $order_by[$keys[0]])
        ->setMaxResults($limit);
        $this->addFilters($qb, $filters);

	    $result = $qb->getQuery()->getArrayResult();
	    return $result;

	}

}
