parameters:
#    freedom_user.example.class: Freedom\UserBundle\Example

services:
#    freedom_user.example:
#        class: %freedom_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
