Freedom\UserBundle\Entity\Userlikeobjective:
    type:  entity
    table: userlikeobjective
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToOne:
        user:
            targetEntity: Freedom\UserBundle\Entity\User
        objective: 
            targetEntity: Freedom\ObjectiveBundle\Entity\Objective
            inversedBy: userlikeobjectives