Freedom\UserBundle\Entity\Userfrienduser:
    type:  entity
    table: userfrienduser
    repositoryClass: Freedom\UserBundle\Entity\UserfrienduserRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        accepted:
            type: boolean
            options:
                default: false
        seen:
            type: boolean
            options:
                default: false
        datecreation:
            type: datetime
    manyToOne:
        user1:
            targetEntity: Freedom\UserBundle\Entity\User
            inversedBy: userfriendusers1
        user2: 
            targetEntity: Freedom\UserBundle\Entity\User
            inversedBy: userfriendusers2