Freedom\UserBundle\Entity\User:
    type:  entity
    repositoryClass: Freedom\UserBundle\Entity\UserRepository
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO