Freedom\UserBundle\Entity\Userfollowobjective:
    type:  entity
    table: userfollowobjective
    repositoryClass: Freedom\UserBundle\Entity\UserfollowobjectiveRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToOne:
        user:
            targetEntity: Freedom\UserBundle\Entity\User
        objective: 
            targetEntity: Freedom\ObjectiveBundle\Entity\Objective
            inversedBy: userfollowobjectives