Freedom\UserBundle\Entity\Userlikeadvice:
    type:  entity
    table: Userlikeadvice
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToOne:
        user:
            targetEntity: Freedom\UserBundle\Entity\User
        advice: 
            targetEntity: Freedom\ObjectiveBundle\Entity\advice
            inversedBy: userlikeadvices