Freedom\UserBundle\Entity\User:
    type:  entity
    repositoryClass: Freedom\UserBundle\Entity\UserRepository
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        firstname:
            type: string
            length: 20
            nullable: false
        lastname:
            type: string
            length: 20
            nullable: false
        pictureName:
            type: string
            length: 255
            nullable: false
        pictureUpdatedAt:
            type: date
    oneToMany:
        userfriendusers1:
            targetEntity: Freedom\UserBundle\Entity\Userfrienduser
            mappedBy: user1
            cascade: ["remove", "persist"]
        userfriendusers2:
            targetEntity: Freedom\UserBundle\Entity\Userfrienduser
            mappedBy: user2
            cascade: ["remove", "persist"]
        usernotifications:
            targetEntity: Freedom\UserBundle\Entity\Notification
            mappedBy: user
            cascade: ["remove", "persist"]
        owngroups:
            targetEntity: Freedom\GroupBundle\Entity\Groups
            mappedBy: user
            cascade: ["remove", "persist"]