Freedom\UserBundle\Entity\User:
    type:  entity
    repositoryClass: Freedom\UserBundle\Entity\UserRepository
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    oneToMany:
        userfriendusers1:
            targetEntity: Freedom\UserBundle\Entity\Userfrienduser
            mappedBy: user1
            cascade: ["remove", "persist"]
        userfriendusers2:
            targetEntity: Freedom\UserBundle\Entity\Userfrienduser
            mappedBy: user2
            cascade: ["remove", "persist"]
        usernotifications:
            targetEntity: Freedom\UserBundle\Entity\Notification
            mappedBy: user
            cascade: ["remove", "persist"]