Freedom\UserBundle\Entity\Userlikestepobjective:
    type:  entity
    table: userlikestepobjective
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToOne:
        user:
            targetEntity: Freedom\UserBundle\Entity\User
        stepobjective: 
            targetEntity: Freedom\ObjectiveBundle\Entity\Stepobjective
            inversedBy: userlikestepobjectives