<?php

namespace Freedom\ObjectiveBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ObjectiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectiveRepository extends EntityRepository
{

	public function myFindOne($id)
	{
	  	$qb = $this->_em->createQueryBuilder();
	  	$qb->select('o')
	     ->from('FreedomObjectiveBundle:Objective', 'o')
	     ->leftJoin('o.steps', 's')
         ->addSelect('s')
	     ->leftJoin('o.user', 'u')
         ->addSelect('u')
	     ->where('o.id = :id')
	     ->setParameter('id', $id);
	    
	    $objectiveArray = $qb->getQuery()->getArrayResult()[0];

	    //Get the number of days left
	    $objectiveObject = $qb->getQuery()->getOneOrNullResult();
	    $objectiveArray['numberOfDays'] = $objectiveObject->getNumberOfDays();

	    //Get advices with user joined
	  	$qb2 = $this->_em->createQueryBuilder();
	  	$qb2->select('a')
	     ->from('FreedomObjectiveBundle:Advice', 'a')
	     ->leftJoin('a.user', 'u')
         ->addSelect('u')
	     ->where('a.objective = :id')
	     ->setParameter('id', $id);

	    $objectiveArray['advices'] = !empty($qb2->getQuery()->getArrayResult()) ? $qb2->getQuery()->getArrayResult() : [];

	    return $objectiveArray;
	}

}
