<?php

namespace Freedom\ObjectiveBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StepobjectiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StepobjectiveRepository extends EntityRepository
{
}
